/**
 * Write the service worker, after the bundle exists.
 *
 * Generated rather than hand-written because the precache list has to name the
 * exact hashed filenames Vite just produced, and a list maintained by hand goes
 * stale the first time someone forgets.
 *
 * The version string is derived from the contents of every file in the build,
 * so a deploy that changes nothing produces the same worker and does not
 * pointlessly re-prompt everyone to reload.
 */

import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const DIST = new URL('../dist/', import.meta.url).pathname

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

const files = walk(DIST)
  .map((f) => relative(DIST, f).split(/[\\/]/).join('/'))
  // The worker cannot sensibly cache itself, and source maps are for us.
  .filter((f) => f !== 'sw.js' && !f.endsWith('.map'))
  .sort()

const hash = createHash('sha256')
for (const file of files) hash.update(file).update(readFileSync(join(DIST, file)))
const version = hash.digest('hex').slice(0, 12)

// Relative, because the app is built with a relative base and may be served
// from a subdirectory. These resolve against the worker's own URL.
const precache = ['./', ...files.map((f) => `./${f}`)]

writeFileSync(join(DIST, 'sw.js'), `/* Generated by scripts/build-sw.mjs. Do not edit. */
const VERSION = ${JSON.stringify(version)}
const CACHE = 'bnotw-' + VERSION
const PRECACHE = ${JSON.stringify(precache, null, 2)}

/**
 * Ignore Vary when matching.
 *
 * Static hosts routinely answer with \`Vary: Origin\`, and Vite marks its module
 * scripts \`crossorigin\`, so the page's own request carries an Origin header
 * that the worker's precache request did not. Left to the default, every
 * lookup misses on that difference alone and the app is broken offline while
 * appearing perfectly cached. Nothing here varies by header: the filenames are
 * content-hashed.
 */
const MATCH = { ignoreVary: true }

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
  // Deliberately no skipWaiting: a page that is already open is running the
  // previous build, and swapping the assets underneath it can 404 a chunk it
  // has not lazily imported yet. The app offers a reload instead.
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys()
    await Promise.all(names.filter((n) => n !== CACHE && n.startsWith('bnotw-')).map((n) => caches.delete(n)))
    await self.clients.claim()
  })())
})

self.addEventListener('message', (event) => {
  // Sent by the page when the player accepts the update.
  if (event.data === 'skip-waiting') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // Navigations go to the network first, so a deploy is picked up as soon as
  // there is a connection, and fall back to the cached shell when there is not.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        return await fetch(request)
      } catch {
        const cache = await caches.open(CACHE)
        return (await cache.match('./', MATCH))
          ?? (await cache.match('./index.html', MATCH))
          ?? Response.error()
      }
    })())
    return
  }

  // Everything else is content-hashed, so the cached copy is always the right
  // one and never needs revalidating.
  event.respondWith((async () => {
    const cached = await caches.match(request, MATCH)
    if (cached) return cached
    try {
      const response = await fetch(request)
      if (response.ok && response.type === 'basic') {
        const cache = await caches.open(CACHE)
        cache.put(request, response.clone())
      }
      return response
    } catch {
      return Response.error()
    }
  })())
})
`)

console.log(`sw.js written — ${files.length} files precached, version ${version}`)
